g++ -c structs.cpp -o structs.o
g++ -c 2DProcessingSrc.cpp -o 2DProcessingSrc.o
g++ -c 3DProcessingSrc.cpp -o 3DProcessingSrc.o
g++ -c Graphs.cpp -o Graphs.o
g++ -c OutputSrc.cpp -o OutputSrc.o
g++ -c InputSrc.cpp -o InputSrc.o
g++ -c InteractiveSrc.cpp -o InteractiveSrc.o
g++ -c Index.cpp -o Index.o