g++ -c structs.cpp -o structs.o -std=c++14
g++ -c 2DProcessingSrc.cpp -o 2DProcessingSrc.o -std=c++14
g++ -c 3DProcessingSrc.cpp -o 3DProcessingSrc.o -std=c++14
g++ -c Graphs.cpp -o Graphs.o -std=c++14
g++ -c OutputSrc.cpp -o OutputSrc.o -std=c++14
g++ -c InputSrc.cpp -o InputSrc.o -std=c++14
g++ -c InteractiveSrc.cpp -o InteractiveSrc.o -std=c++14
g++ -c Index.cpp -o Index.o -std=c++14